### ISSUE TITLE
Add Tags for Release Versions

### ISSUE THREAD

**Issue by asayler** [ndunand/moodle-qtype_regexp#1]
Would it be possible to tag the release versions of this repo in git? This makes it much simpler to clone a specific version of the repo and eases the burden of downstream release management, especially for those of us building Moodle installs via scripts (e.g. for Docker).

E.g.
Running:
```
git tag 2016071400 4096da7a17a0f350e70a358e95560bc9ab35259a
git push --tags
```

Allows one to replace:
```
git clone --recursive --single-branch \
"https://github.com/ndunand/moodle-qtype_regexp.git" \
"${MOODLE_CODE_PATH}/question/type/regexp" \
&& cd "${MOODLE_CODE_PATH}/question/type/regexp" \
&& git checkout 4096da7a17a0f350e70a358e95560bc9ab35259a \
&& cd
```

With the cleaner:
```
git clone --recursive --single-branch -b 2016071400 \
"https://github.com/ndunand/moodle-qtype_regexp.git" \
"${MOODLE_CODE_PATH}/question/type/regexp" \
```

I'd file this as a pull quest, but github does not currently allow importing git metadata such as tags via pull request -- tags can only be applied by someone with commit access to the repo itself.

**Comment by ndunand** [comment]
Okay, done
